In [2]:
import numpy as np

temperature = np.array([[23, 25, 28, 30], [21, 22, 26, 29], [24, 27, 29, 32]])
humidity = np.array([[60, 65, 70, 75], [55, 58, 68, 72], [62, 67, 74, 78]])

In [3]:
mean_temperature = np.mean(temperature)
mean_humidity = np.mean(humidity)
print(f"Mean Temperature: {round(mean_temperature,2)}, \n Mean Humidity:, {round(mean_humidity,2)}")

Mean Temperature: 26.33, 
 Mean Humidity:, 67.0


In [4]:
max_h = np.max(humidity)
print(max_h)

78


In [5]:
comfort_index = 0.8*temperature*0.2*humidity
print(f"comfort index is\n{comfort_index}")

comfort index is
[[220.8  260.   313.6  360.  ]
 [184.8  204.16 282.88 334.08]
 [238.08 289.44 343.36 399.36]]


In [6]:
# Compute the variance of temperature along each row.
variance_temperature = np.var(temperature, axis=1)
print(variance_temperature)

[ 7.25 10.25  8.5 ]


In [7]:
prices = np.array([[200, 150, 300], [120, 180, 250], [100, 140, 190]])
category_discounts = np.array([[5], [8], [12]])
discount = 0.10*prices
discounted_prices = prices - discount
print(discounted_prices)

[[180. 135. 270.]
 [108. 162. 225.]
 [ 90. 126. 171.]]


In [8]:
category_s = (category_discounts/100)

print(category_s)


[[0.05]
 [0.08]
 [0.12]]


In [9]:
finalprice = prices -discount - category_s
print(finalprice)

[[179.95 134.95 269.95]
 [107.92 161.92 224.92]
 [ 89.88 125.88 170.88]]


In [10]:
numlist = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
numarray = np.array(numlist)
print(numarray)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
numarray = numarray.reshape(2, 5)
print(numarray)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [12]:
print(numarray.shape)
# 2x5 matrix

(2, 5)


In [13]:
numarray = numarray.reshape(5, 2)
print(numarray)
# 5x2 matrix

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [15]:
numarray = numarray.reshape(1,10)
print(numarray)

[[ 1  2  3  4  5  6  7  8  9 10]]
